### ISSUE TITLE
Support for Youtube / Youtube Music

### ISSUE THREAD

**Issue by Conceptron** [ddddxxx/MusicPlayer#9]

**Comment by ddddxxx** [comment]
Youtube Music is not scriptable. You can use `SystemMedia` instead.

**Comment by Conceptron** [comment]
Is that a music player?

**Comment by ddddxxx** [comment]
No, I'm referring to [MusicPlayers.SystemMedia](https://github.com/ddddxxx/MusicPlayer/blob/master/Sources/MusicPlayer/Players/SystemMedia.swift). It read system wide media player like Control Center on your Mac.

Edit: If you're using LyricsX, please enable "Use system wide now playing application" from lab, and select "Auto" for preferred music player.

**Comment by Conceptron** [comment]
Ah. How do I select it? Should I select the "Auto" option in preferences?
![image](https://user-images.githubusercontent.com/35289454/132119309-425655fa-d87b-46ab-90c8-b2b0fad9be45.png)

**Comment by ddddxxx** [comment]
You also need to enable "Use system wide now playing application" from lab, as it's an experimental feature in LyricsX.

**Comment by Conceptron** [comment]
Thank you! It works for the Youtube Music app :)
